import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "../components/landing/navbar";
import StudentClass from "@/components/misclases/StudentClass"; // Import the StudentClass component
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Define the student data
  const studentData = {
    name: "Mathematics 101",
    professor: "Dr. John Doe",
    fecha: "mañana",
    hora: "2:15",
  };

  return (
    <html lang="en">
      <body>
        <Navbar />
        <StudentClass student={studentData} />
        {children}
      </body>
    </html>
  );
}
